### ISSUE TITLE
Confusing instructions for Section E

### ISSUE THREAD

**Issue by albertoe** [ganrad/aks-aspnet-sqldb-rest#16]
Regarding Section E: Deploy an Azure Pipelines Agent on the Linux VM

Should we use the values.yml from the Az-DevOps-Agent-On-AKS repository or should we adapt the values.yml file from aks-aspnet-sqldb-rest repository.

I got stuck on Step F when running the pipeline as it is reporting the following error:
"No Docker file matching  /azp/agent/_work/1/s/Dockerfile  was found"

And it seems that this is due to the values.yml file being used to create the agent.

**Comment by ganrad** [comment]
@albertoe To deploy the self-hosted Azure DevOps agent on a VM/AKS, follow the instructions in the ‘Az-DevOps-Agent-On-AKS’ GitHub repo. URL/Link for this GitHub repo. is provided in section E.  The Helm chart for deploying the agent is included within this repo. As well.   After deploying the agent, you can come back to this repo and continue with section F.  The helm chart included in this repo. Is for deploying the claims-api application.  Hope this clarifies.
