### ISSUE TITLE
Step B10 Install docker-ce container runtime is failing. 

### ISSUE THREAD

**Issue by boshis** [ganrad/aks-aspnet-sqldb-rest#7]
When I got to this step running the command
$ sudo yum install -y docker-ce docker-ce-cli containerd.io

Returns the following errors and does not allow me to continue with the install

Error: moby-containerd conflicts with containerd.io-1.2.13-3.2.el7.x86_64
Error: moby-runc conflicts with containerd.io-1.2.13-3.2.el7.x86_64

**Comment by ganrad** [comment]
@boshis you probably already have a version of docker-ce/containerd installed on your machine.  Try [uninstalling the existing version](https://docs.docker.com/engine/install/centos/) and reinstalling docker again.
