### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by agile-andrew** [ganrad/aks-aspnet-sqldb-rest#9]
README.md:860 has an interesting typo that we might want to fix 😂  ... (unless there's an alternate meaning of this word that I'm unaware of)

> An ingress controller acts as a load balancer **_cum_** reverse proxy

**Comment by ganrad** [comment]
@drewpenn K8S ingress controllers such as Nginx and Traefik act as both a **load balancer and reverse proxy**.  They distribute the incoming http request traffic across multiple backend server instances (load balancer http requests) & they also play the role of a reverse proxy ~ hide the backend server IP's from consuming apps, perform request throttling, allow black listing of client IP's, compress responses, cache static responses, perform SSL session termination & so forth.  Hope this answers your question.

**Comment by ganrad** [comment]
Fixed the typo @drewpenn.  Thanks for pointing this out !
